### ISSUE TITLE
TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by oopsaleem** [ctamisier/generator-jhipster-quasar#5]
`I am using latest jhipster 7.2.0`

application {
  config {
    applicationType monolith
    authenticationType jwt
    baseName myapp
    blueprints [generator-jhipster-quasar]
    buildTool maven
    cacheProvider ehcache
    clientFramework quasar
    clientPackageManager npm
    clientTheme none
    databaseType sql
    devDatabaseType h2Disk
    enableHibernateCache true
    enableTranslation false
    jhipsterVersion "7.1.0"
    languages [en, fr]
    nativeLanguage en
    otherModules [generator-jhipster-quasar]
    packageName ca.pla.myapp
    prodDatabaseType postgresql
    withAdminUi true
  }
}

`Above config run into below error`

 App • Running "vuelidate-rules" Quasar App Extension...
 App • Extension(vuelidate-rules): Extending quasar.conf...
 App • Chaining "UI" Webpack config
 App •  WAIT  • Compiling of "UI" in progress...

 • Compiling:
 └── UI ███████████████████  92% sealing asset processing

/Users/tomcat/IdeaProjects/quasar-app/quasar/node_modules/merge-jsons-webpack-plugin/index.js:20
                .reduce((acc, curr) => this.mergeDeep(acc, curr));
                 ^

[  TypeError: Reduce of empty array with no initial value
  
  - Array.reduce

**Comment by oopsaleem** [comment]
Issue resolved if selected Yes to Internationalization then choose any language.

**Comment by ctamisier** [comment]
Thanks for reporting this, it is indeed an issue.
