### ISSUE TITLE
The translation is not loaded when I skip server

### ISSUE THREAD

**Issue by mabujaber** [ctamisier/generator-jhipster-quasar#6]
I tried to use a quasar generator without server-side code and I got most of the label is not translated!

**Comment by ctamisier** [comment]
Thanks for noticing this !

You can actually run this additional command:
`quasar serve -p 8080 quasar/dist` (which will host i18n files)

**Comment by mabujaber** [comment]
I was running the same inside the quasar folder but still face the same

**Comment by ctamisier** [comment]
Hm, it's strange as it should work.
![image](https://user-images.githubusercontent.com/766263/141690667-a255a60b-bccd-42b4-b053-ff99b9e65f7d.png)

**Comment by mabujaber** [comment]
did you generate only frontend?

**Comment by ctamisier** [comment]
Oh ok, you need to run
`npx quasar build` before
